### ISSUE TITLE
Governmental vendors invoice NCF Type  

### ISSUE THREAD

**Issue by jpshort** [raulovallet/l10n-dominicana-pro#36]
#### Video/Screenshot link (optional)
![image](https://github.com/raulovallet/l10n-dominicana-pro/assets/12738468/81bed74d-aeb1-4944-b1c1-727bee0acebf)

**Comment by raulovallet** [comment]
Solved with [Commit](https://github.com/raulovallet/l10n-dominicana-pro/commit/feb7a8224494c594327b78d4ebdf9b2cbc83bb5a)
